# Generated by Django 5.2.12 on 2026-03-27 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_event_address_event_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='address',
        ),
        migrations.AddField(
            model_name='registration',
            name='notification_sent',
            field=models.BooleanField(default=False, verbose_name='Уведомление отправлено'),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_type',
            field=models.CharField(choices=[('club', 'Клуб по интересам'), ('theatre', 'Театральный кружок'), ('craft', 'Творческая мастерская'), ('masterclass', 'Мастер-класс'), ('art', 'Художественная студия'), ('lecture', 'Лекция'), ('meeting', 'Встреча')], default='club', max_length=20, verbose_name='Тип'),
        ),
    ]
