# Generated by Django 5.2.12 on 2026-03-28 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_event_address_registration_notification_sent_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='notification_sent',
        ),
    ]
